name: Gradle Library Release Workflow

on:
  workflow_call:
    inputs:
      SOURCE_DIR:
        description: 'Path to source directory. For monorepos, this is the path to the library source directory. Leave empty for the root directory.'
        required: false
        default: ''
        type: string
      MODULES:
        description: 'Comma-separated list of module names to build (e.g. "core,utils,api").'
        required: true
        type: string
      API_FILE:
        description: 'Path to API file relative to the module directory.'
        required: false
        default: 'api/api.txt'
        type: string
      VERSION_FILE:
        description: 'Path to version file relative to the source directory.'
        required: false
        default: 'version.txt'
        type: string
      GITHUB_APP_ID:
        description:
          "App ID for a GitHub App that is allowed to push directly to the default branch. Eg, App ID on:
          https://github.com/organizations/guardian/settings/apps/gu-gradle-library-release"
        default: '1576314' # Only for use by the Guardian!
        required: false # ...but if you're not the Guardian, you'll want to set this explicitly
        type: string
    secrets:
      SONATYPE_TOKEN:
        description: 'Sonatype authentication token, colon-separated (username:password) - https://central.sonatype.org/publish/generate-token/'
        required: true
      PGP_PRIVATE_KEY:
        description:
          "A passphrase-less PGP private key used to sign artifacts, commits, & tags.
          Should be in normal plaintext (ASCII-armored) format, starting 'BEGIN PGP PUBLIC KEY BLOCK', with no additional BASE64-encoding.
          The passphrase can be removed from an existing key using 'gpg --edit-key <key-id> passwd' : https://unix.stackexchange.com/a/550538/46453"
        required: true
      GITHUB_APP_PRIVATE_KEY:
        description:
          "See https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/managing-private-keys-for-github-apps#generating-private-keys
          Should be in normal plaintext format, starting '-----BEGIN RSA PRIVATE KEY-----'"
        required: true
    outputs:
      RELEASE_VERSION:
        description: "The un-prefixed version number of the release, eg '3.0.1'"
        value: ${{ jobs.push-release-commit.outputs.release-version }}
      RELEASE_TYPE:
        description: "Either 'FULL_MAIN_BRANCH' or 'PREVIEW_FEATURE_BRANCH' - whether this is a full release or a pre-release"
        value: ${{ jobs.init.outputs.release-type }}

env:
  GITHUB_REPO_URL: ${{ github.server_url }}/${{ github.repository }}

jobs:
  init:
    name: 🔒 Init
    runs-on: ubuntu-latest
    outputs:
      pgp-key-fingerprint: ${{ steps.act.outputs.pgp-key-fingerprint }}
      pgp-key-email: ${{ steps.act.outputs.pgp-key-email }}
      release-type: ${{ steps.act.outputs.release-type }}
      version-suffix: ${{ steps.act.outputs.version-suffix }}
    steps:
      - id: act
        uses: guardian/gha-scala-library-release-workflow/actions/init@main
        with:
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}

  versioning:
    name: 🎊 Versioning
    needs: init
    runs-on: ubuntu-latest
    outputs:
      library-build-major-java-version: ${{ steps.versioning.outputs.library-build-major-java-version }}
    steps:
      - name: Versioning
        id: versioning
        uses: guardian/gha-gradle-library-release-workflow/.github/actions/versioning@ab/only-commit-api-files-if-changed
        with:
          SOURCE_DIR: ${{ inputs.SOURCE_DIR }}
          MODULES: ${{ inputs.MODULES }}
          API_FILE: ${{ inputs.API_FILE }}
          VERSION_FILE: ${{ inputs.VERSION_FILE }}
          VERSION_SUFFIX: ${{ needs.init.outputs.version-suffix }}

  push-release-commit:
    name: 🔒 Push Release Commit
    needs: [versioning, init]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.push-release-commit.outputs.release-tag }}
      release-notes-url: ${{ steps.push-release-commit.outputs.release-notes-url }}
      release-version: ${{ steps.push-release-commit.outputs.release-version }}
      release-commit-id: ${{ steps.push-release-commit.outputs.release-commit-id }}
      version-file-path: ${{ steps.push-release-commit.outputs.version-file-path }}
      version-file-release-sha: ${{ steps.push-release-commit.outputs.version-file-release-sha }}
      version-file-post-release-content: ${{ steps.push-release-commit.outputs.version-file-post-release-content }}
      temporary-branch: ${{ steps.push-release-commit.outputs.temporary-branch }}
    steps:
      - name: Push Release Commit
        id: push-release-commit
        uses: guardian/gha-gradle-library-release-workflow/.github/actions/push-release-commit@ab/only-commit-api-files-if-changed
        with:
          GITHUB_APP_ID: ${{ inputs.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          SOURCE_DIR: ${{ inputs.SOURCE_DIR }}
          VERSION_FILE: ${{ inputs.VERSION_FILE }}
          API_FILE: ${{ inputs.API_FILE }}
          API_UPDATED_MODULES: ${{ needs.versioning.outputs.api-updated-modules }}
          RELEASE_TYPE: ${{ needs.init.outputs.release-type }}
          VERSION_SUFFIX: ${{ needs.init.outputs.version-suffix }}
          GITHUB_REPO_URL: ${{ env.GITHUB_REPO_URL }}

  create-artifacts:
    name: 🎊 Create artifacts
    needs: [init, versioning, push-release-commit]
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ needs.push-release-commit.outputs.release-version }}
      LIBRARY_BUILD_MAJOR_JAVA_VERSION: ${{ needs.versioning.outputs.library-build-major-java-version }}
    outputs:
      artifact-sha256sums: ${{ steps.create-artifacts.outputs.artifact-sha256sums }}
    steps:
      - name: Create Artifacts
        id: create-artifacts
        uses: guardian/gha-gradle-library-release-workflow/.github/actions/create-artifacts@ab/only-commit-api-files-if-changed
        with:
          SOURCE_DIR: ${{ inputs.SOURCE_DIR }}
          MODULES: ${{ inputs.MODULES }}
          VERSION_FILE: ${{ inputs.VERSION_FILE }}
          RELEASE_VERSION: ${{ needs.push-release-commit.outputs.release-version }}
          RELEASE_COMMIT_ID: ${{ needs.push-release-commit.outputs.release-commit-id }}

  sign:
    name: 🔒 Sign
    needs: [init, push-release-commit, create-artifacts]
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/gha-scala-library-release-workflow/actions/sign@main
        with:
          github-app-id: ${{ inputs.GITHUB_APP_ID }}
          github-app-private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
          pgp-key-email: ${{ needs.init.outputs.pgp-key-email }}
          pgp-key-fingerprint: ${{ needs.init.outputs.pgp-key-fingerprint }}
          pgp-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          release-type: ${{ needs.init.outputs.release-type }}
          release-tag: ${{ needs.push-release-commit.outputs.release-tag }}
          release-commit-id: ${{ needs.push-release-commit.outputs.release-commit-id }}
          artifact-sha256sums: ${{ needs.create-artifacts.outputs.artifact-sha256sums }}

  sonatype-release:
    name: 🔒 Sonatype Release
    needs: [push-release-commit, sign]
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/gha-scala-library-release-workflow/actions/sonatype-release@main
        with:
          release-version: ${{ needs.push-release-commit.outputs.release-version }}
          sonatype-token: ${{ secrets.SONATYPE_TOKEN }}

  update-github:
    name: 🔒 Update GitHub
    needs:  [init, push-release-commit, sign, sonatype-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Update GitHub
        uses: guardian/gha-scala-library-release-workflow/actions/update-github@ab/make-post-release-version-file-update-optional
        with:
          github-app-id: ${{ inputs.GITHUB_APP_ID }}
          github-app-private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }} }
          release-type: ${{ needs.init.outputs.release-type }}
          release-tag: ${{ needs.push-release-commit.outputs.release-tag }}
          release-version: ${{ needs.push-release-commit.outputs.release-version }}
          release-notes-url: ${{ needs.push-release-commit.outputs.release-notes-url }}
          temporary-branch: ${{ needs.push-release-commit.outputs.temporary-branch }}
          version-file-path: ${{ needs.push-release-commit.outputs.version-file-path }}
          version-file-release-sha: ${{ needs.push-release-commit.outputs.version-file-release-sha }}
          version-file-post-release-content: ${{ needs.push-release-commit.outputs.version-file-post-release-content }}
          commit-snapshot-version: "false" # We don't use the -SNAPSHOT suffix in Gradle libraries